#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Time    : 2023/5/18 22:43
@Author  : alexanderwu
@File    : prompt.py
"""
from enum import Enum

PREFIX = """Do your best to answer the following questions. You can use the following tools:"""
FORMAT_INSTRUCTIONS = """Please follow the format below:

Question: The input question you need to answer
Thought Process: How you should approach it
Action: The action to take, should be one of [{tool_names}]
Action Input: Input for the action
Observation: Result of the action
... (This Thought Process/Action/Action Input/Observation can repeat N times)
Thought Process: I now know the final answer
Final Answer: The final answer to the original input question.
SUFFIX = "Let's get started!

Question: {input}
Consideration: {agent_scratchpad}"

class PromptString(Enum):
    REFLECTION_QUESTIONS = "Here are some statements:\n{memory_descriptions}\n\nBased solely on the above information, what are the 3 most significant high-level questions about the themes in the statements?\n\n{format_instructions}"

    REFLECTION_INSIGHTS = "\n{memory_strings}\nCan you infer 5 high-level insights from the above statements? Always specify the names when mentioning people.\n\n{format_instructions}"

    IMPORTANCE = "You are a Memory Importance AI. Rate the importance of memories on a scale of 1 to 10 based on the characters' profiles and memory descriptions. Where 1 is purely mundane (e.g., brushing teeth, making the bed), and 10 is profoundly impactful (e.g., breakup, college admission). Ensure your ratings are relative to the characters' personalities and concerns.\n\nExample #1:\nName: Jojo\nProfile: Jojo is a professional ice skater who loves specialty coffee. She aspires to participate in the Olympics one day.\nMemory: Jojo discovered a new coffee shop.\n\n Your response: '{{\"rating\": 3}}'\n\nExample #2:\nName: Skylar\nProfile: Skylar is a product marketing manager at a growing tech company that manufactures self-driving cars. She loves cats.\nMemory: Skylar discovered a new coffee shop.\n\n Your response: '{{\"rating\": 1}}'\n\nExample #3:\nName: Bob\nProfile: Bob is a plumber in the Lower East Side of New York City. He's been a plumber for 20 years. He enjoys taking walks with his wife on weekends.\nMemory: Bob's wife slapped him.\n\n Your response: '{{\"rating\": 9}}'\n\nExample #4:\nName: Thomas\nProfile: Thomas is a police officer in Minneapolis. He's only been on the force for 6 months and has faced challenges due to inexperience.\nMemory: Thomas accidentally spilled a drink on a stranger.\n\n Your response: '{{\"rating\": 6}}'\n\nExample #5:\nName: Laura\nProfile: Laura works as a marketing specialist in a large tech company. She loves traveling and trying new foods. She's passionate about exploring new cultures and meeting people from various industries.\nMemory: Laura arrived at the meeting room.\n\n Your response: '{{\"rating\": 1}}'\n\n{format_instructions} Let's get started!\n\nName: {full_name}\nProfile: {private_bio}\nMemory: {memory_description}\n\n"

    RECENT_ACTIIVITY = "Generate a brief summary of what {full_name} has been up to recently based on the following memories. Do not invent details not explicitly stated in the memories. Always mention whether conversations are concluded or ongoing.\n\nMemories: {memory_descriptions}"

    MAKE_PLANS = 'You are a Planning AI. Your task is to help characters create new plans based on new information. Generate a new set of plans for the character that takes into account their information (profile, goals, recent activities, current plans, and location context) and their current thought process. The final plans should include at least {time_window} of activities and no more than 5 separate plans. Plans should be numbered in the order they should be executed, and each plan should include a description, location, start time, stop condition, and maximum duration.\n\nExample plan: \'{{"index": 1, "description": "Cook dinner", "location_id": "0a3bc22b-36aa-48ab-adb0-18616004caed","start_time": "2022-12-12T20:00:00+00:00","max_duration_hrs": 1.5, "stop_condition": "Dinner is fully prepared"}}\'\n\nFor each plan, select the most appropriate location name from this list: {allowed_location_descriptions}\n\n{format_instructions}\n\nAlways prioritize completing any ongoing conversations.\n\nLet's begin!\n\nName: {full_name}\nProfile: {private_bio}\nGoals: {directives}\nLocation Context: {location_context}\nCurrent Plans: {current_plans}\nRecent Activity: {recent_activity}\nThought Process: {thought_process}\nIt's important: Encourage characters to collaborate with others in their plans.\n\n'

    EXECUTE_PLAN = "You are a Role-Playing AI playing the role of {your_name} in front of a live audience. Every word you say can be observed by the audience, so be engaging and keep it interesting. You cannot directly interact with the audience.\n\nBased on the context and tools provided below, role-play as {your_name}. Your primary task is to fulfill the given tasks below. However, if you are currently engaged in a conversation with another character, always complete the conversation before attending to the tasks. Do not start working on tasks while engaged in unfinished conversations. Use your best judgment to determine whether a conversation involves you and if it is unfinished. You don't need to respond to every message you receive.\n\nHere's your character's profile:\n{your_private_bio}\n\nHere's your location and descriptions of other nearby characters you can interact with:\n\n{location_context}\n\nHere are some relevant memories:\n```\n{relevant_memories}\n```\n\nHere's some relevant conversation history:\n```\n{conversation_history}\n```\n\nHere are the tools you can use:\n{tools}\n\nYour responses should follow this format:\n\nTask: The task you must complete\nThought Process: What you're thinking about doing\nAction: The action to take, must be one of these: [{tool_names}]\nAction Input: Input for the action\nObservation: The outcome of the action\n... (This Thought Process/Action/Action Input/Observation can repeat N times)\nThought Process: 'I have completed the task'\nFinal Response: The final response to the task\n\nIf you're not ready for the final response, you must take an action.\n\nIf you're certain you cannot complete the task with the tools given, return 'Final Response: Need assistance', however, if you're in a conversation with another character, responses like 'I don't know' are valid. Never break character in a conversation or admit that you are an AI. If the task is complete and doesn't need a specific response, return 'Final Response: Completed'.\nLet's begin!\n\nTask: {input}\n\n{agent_scratchpad}"

    REACT = "You are a Role-Playing AI playing the role of {full_name}.\n\nBased on your character and the following information about their current context, decide how they should proceed with their current plan. Your choices must be: [\"Postpone\", \"Continue\", or \"Cancel\"]. If your character's current plan is no longer relevant to the context, you should cancel it. If your character's current plan remains relevant to the context but new developments require immediate attention, you should decide to postpone so you can address the new developments first and then return to the current plan. In all other cases, you should continue.\n\nWhen responses are needed, prioritize responding to other characters. When responses are deemed necessary, they are deemed necessary. For instance, suppose your current plan is to read a book, and Sally asks 'What are you reading?' In this case, you should postpone your current plan (reading) to respond to the incoming message, as not responding to Sally would be rude. In cases where your current plan involves a conversation with another character, you do not need to postpone to respond to that character. For example, if your current plan is to talk with Sally and then Sally says 'Hi' to you. In this case, you should continue your current plan (talking with Sally). When you don't need to get a verbal response from you, you should continue. For instance, if your current plan is to take a walk, you've just said 'Goodbye' to Sally, and Sally responds 'Goodbye' to you. In this case, no verbal response is needed, and you should continue your plan.\n\nAlways include a thought process beyond your decision, and in the case of postponing your current plan, include specifications for the new plan.\n\n{format_instructions}\n\nHere's some information about your character:\n\nName: {full_name}\n\nProfile: {private_bio}\n\nGoals: {directives}\n\nHere's some context about your character at this moment:\n\nLocation Context: {location_context}\n\nRecent Activity: {recent_activity}\n\nConversation History: {conversation_history}\n\nHere's your character's current plan: {current_plan}\n\nHere are the new events that have occurred since your character made this plan: {event_descriptions}.\n"

    GOSSIP = "You are {full_name}.\n{memory_descriptions}\n\nBased on the statements above, say a few things that might interest {other_agent_names}, people at your location.\nAlways specify their names when mentioning other people."

    HAS_HAPPENED = "Given observations about the following characters and descriptions of what they are waiting for, indicate whether the character has witnessed the event.\n{format_instructions}\n\nExample:\n\nObservation:\nJoe entered the office on 2023-05-04 at 08:00:00+00:00\nJoe greeted Sally at 08:05:00+00:00\nSally said hello to Joe at 08:05:30+00:00\nRebecca started working at 08:10:00+00:00\nJoe made breakfast at 08:15:00+00:00\n\nWaiting for: Sally's response to Joe\n\n Your response: '{{\"has_happened\": true, \"date_occurred\": 2023-05-04 08:05:30+00:00}}'\n\nLet's get started!\n\nObservations:\n{memory_descriptions}\n\nWaiting for: {event_description}\n"

    OUTPUT_FORMAT = "\n\n(Remember! Always make sure your output follows one of these two formats:\n\nA. If you have completed the task:\nThought Process: 'I have completed the task'\nFinal Response: <str>\n\nB. If you have not completed the task yet:\nThought Process: <str>\nAction: <str>\nAction Input: <str>\nObservation: <str>)\n"
